eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: say-hello-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.8:3306/eshop?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: eshop
    password: eshop
curator:
  connectString: 192.168.1.5:2181,192.168.1.6:2181,192.168.1.7:2181
  connectionTimeoutMs: 5000
  elapsedTimeMs: 5000
  retryCount: 5
  sessionTimeoutMs: 60000    
jedisCluster:
  nodesString: 192.168.1.5:7001,192.168.1.5:7002,192.168.1.6:7003,192.168.1.6:7004,192.168.1.7:7005,192.168.1.7:7006
  pass: redis-pass